# Use an official Python runtime as the base image
FROM python:3.9

# Set the working directory in the container
WORKDIR /app

# Copy the script and requirements file to the container
COPY create_gcp_buckets.py .
COPY docker-requirements.txt .

# Install the required Python packages
RUN pip install -r docker-requirements.txt

# Set the command to run the script
CMD python create_gcp_buckets.py
 